### ISSUE TITLE
Edit from different device

### ISSUE THREAD

**Issue by JulianGoesPro** [thm-projects/arsnova.click#2]
Hi,

it looks like I am unable to edit an already finished lecture on a different device.

Let me describe the use case: I created "Lecture Dr. Nold" on my MacBook but wanted to edit it to keep the questions up2date but it looks like the only way to edit it is on that specific MacBook, exporting and importing will result in "losing" "Lecture Dr. Nold" as the link which I don't really want.

Is there a way around it? ...like deleting "Lecture Dr. Nold" from the server so I can re-upload the jston with the original name?

Thanks a lot!

<img width="1440" alt="Screenshot 2019-05-19 at 11 46 34" src="https://user-images.githubusercontent.com/11023597/57980433-f854cc00-7a2b-11e9-9985-871647207378.png">

**Comment by trayhem** [comment]
The name is unique for the quiz across the application - unfortunately you cannot take the quiz name with you. We have an early phase of syncing the quizzes across an account but this is currently not stable enough for production usage. So this feature may come in future but I cannot give any hint when the feature will arive.

A workaround would be: Export the quiz from your laptop, then delete it. After that you can import the session on your other device and the server will accept the quiz name because it is not yet taken.
